name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    contents : write
    write    : read
    
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        read        : rw.rw.rw.rw
        read        : rwx.rwx.rwx
        Result      : 
        Sum         : B 3 1
        Search      : =
        Example      : 
=
h
1
B
 
∑
b
=
1
B
C
b
θ
b
−
R
b
θ
b
+
h
2
·
E
L
A
T
¯
o
,
 
L
O
N
¯
o
,
θ
¯
3
d
B
,
 
α
+
h
3
·
C
o
s
t
G
b
p
s
B
,
θ
b

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npx webpack
